Jusicool-Ver-2-0/Jusicool-Server

- src/accounts/services/email.py
- src/accounts/templates/mail_template.html
email 전송 템플릿을 구현했습니다.
- email 전송 템플릿 제작
- email service 로직 변경
> [feat] email 전송 템플릿 구현

- .github/workflows/prod-cd.yml
- .github/workflows/stage-cd.yml
- Dockerfile
- appspec.yml
- scripts/deploy.sh
- scripts/prod.sh
- scripts/stage.sh
서비스 배포를 구성했습니다.
- workflows 작성
- deploy scripts 작성
- appspec.yml 작성
> [feat] 서비스 배포 구성

- scripts/deploy.sh
배포 스크립트를 수정했습니다
- deploy.sh 수정
> [fix] 배포 스크립트 수정

- Dockerfile
- src/core/settings/base.py
도커파일과 타임존 설정에서 발생하는 배포 에러들을 수정했습니다.
- Dockerfile 수정
- settings.base.py timezone 오타 수정
> [fix] Dockerfile, Timezone 세팅 수정

- scripts/deploy.sh
- src/core/settings/base.py
배포 scripts 권한 에러 수정하고 오타를 수정했습니다.
- urls.py
- deploy.sh
> [fix] 배포 scripts 권한 에러 수정

- Dockerfile
- src/core/settings/base.py
- src/core/settings/local.py
- src/core/settings/stage.py
stage 애플리케이션 배포 설정했습니다
- dockerfile 수정
- settings 수정
> [feat] stage 애플리케이션 배포 설정

- Dockerfile
- scripts/prod.sh
- scripts/stage.sh
도커 네트워크를 설정했습니다
- Dockerfile 수정
- Docker run 명령어 변경 (네트워크 옵션 추가)
> [feat] 도커 네트워크 설정

- src/core/urls.py
- src/holding/serializers.py
- src/holding/services/my.py
- src/holding/urls.py
- src/holding/views.py
- src/holding/views/my.py
자신이 홀딩중인 리스트를 조회하는 api를 제작했습니다.
- holding app 변경
> [feat] 내가 홀딩중인 리스트 조회

- pyproject.toml
- src/core/__init__.py
- src/core/celery.py
- src/core/settings/base.py
- src/user/services/email.py
- src/user/tasks.py
기존에 동기적으로 전송되던 인증 메일을 celery를 사용해 비동기적으로 전송되게 수정했습니다
- celery 디펜던시 추가
- celery 세팅
- 메일서비스 변경
- 도커파일 수정
> [feat] celery를 사용한 email 비동기 전송

- src/core/settings/base.py
- src/order/serializers.py
- src/order/services/crypto_my.py
- src/order/urls.py
- src/order/views/crypto_my.py
보유중인 peding 상태의 주문을 조회하는 api를 만들었습니다
- order crypto my api
- fix minor bug
> [feat] 보유중인 peding 상태의 주문 조회

- src/order/services/crypto_my.py
- src/order/views.py
- src/order/views/crypto_my.py
order 조회 api를 구현했습니다
- order app
> [feat] order 조회 api

- Dockerfile
- docker-entrypoint.sh
> [feat] docker-entrypoint 구성

- src/core/settings/base.py
> [fix] celery host 변경

- docker-entrypoint.sh
기존 경로에서 core.celery로 변경했습니다.
잘못된 worker 설정을 수정했습니다.
> [fix] celery worker 설정 변경

- docker-compose.yml
- docker-entrypoint.sh
- scripts/prod.sh
- scripts/stage.sh
- src/core/settings/base.py
- src/core/settings/local.py
- src/core/settings/stage.py
celery 도커라이징
redis, postgres도 도커화
> [feat] celery 도커라이징

- .github/workflows/stage-cd.yml
stage 배포시에 사용시 ssh 연결 설정을 바꿨습니다
> [workflows] stage deploy ssh 설정 변경

- Dockerfile
> [docker] 도커 빌드 최적화

- docker-compose.yml
- poetry.lock
- src/order/serializers.py
- src/order/services/month.py
- src/order/urls.py
- src/order/views/month.py
한달간 주문 수, 수익률 조회 api를 구현했습니다.
- 라이브러리 버전을 업데이트했습니다.
- 오타를 수정했습니다.
> [feat] 한달간 주문 수, 수익률 조회 api

- src/holding/serializers.py
- src/holding/services/my.py
- src/holding/views/my.py
> [feat] 내 자산 조회 api

- docker-compose.yml
docker-compose depends에 없는 의존성을 삭제했습니다.
> [fix] docker-compose depends 설정 수정

- src/core/settings/base.py
> [fix] static root 설정 추가

- src/order/services/month.py
한달수익 rate 자료형을 float에서 int로 변경하였습니다
> [fix]한달 수익 rate 자료형 int 설정

- src/order/services/month.py
Reverts Jusicool-Ver-2-0/Jusicool-Server#107
> Revert "[fix]한달 수익 rate 자료형 int 설정"

- .github/workflows/prod-cd.yml
- .github/workflows/stage-cd.yml
> [workflow] 배포 스크립트 수정 

- src/market/services/search.py
- src/market/urls.py
- src/market/views/search.py
> [feat] market search

- src/order/serializers.py
- src/order/services/my.py
> [update] my order query

- src/order/services/my.py
> [update] order 조회시에 최신순 정렬

- src/order/services/month.py
monthly rate에 proceed와 quentity 곱연산을 수정했습니다.
> [fix] proceed와 quentity 곱연산 수정

- src/market/serializers.py
- src/market/services/search.py
- src/market/urls.py
- src/market/views/search.py
인기 검색어를 구현했습니다.
가중치 계산은 나중에 개선하겠습니다
> [feat] 인기검색어 구현

- src/community/serializers.py
> [feat] 나의 게시글인지 확인하는 필드 추가

- src/community/serializers.py
> [fix] 커뮤니티 게시글 반환시 username, created_at 포함

- src/market/tasks/crypto/update.py
- src/market/tasks/stock/update.py
market update task 실패시 재실행 파라미터를 추가했습니다.
> [refactor] market update task 실패시 재실행 파라미터 추가

- src/user/services/email.py
- src/user/services/user.py
> [feat] signup logic
